name: heritage-dev

services:
    postgres:
        container_name: postgres
        image: postgres:17.5
        environment:
            POSTGRES_DB: "heritage"
            POSTGRES_PASSWORD: "password"
            POSTGRES_USER: "postgres"
        ports:
            - 5432:5432
        volumes:
            - pg_data:/var/lib/postgresql/data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - reverse_proxy

    rest-api:
        container_name: rest-api
        build:
            context: ./api
            dockerfile: ./docker/dev.Dockerfile
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            PASSWORD: "DEV"
        volumes:
            - ./api/public:/app/public
            - ./api/required:/app/required
        ports:
            - 8080:8080
        networks:
            - reverse_proxy

    server:
        container_name: server
        image: caddy:2.10.0-alpine
        environment:
            DOMAIN: "naszrod.local"
        restart: unless-stopped
        ports:
            - 443:443
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./server/dev.Caddyfile:/etc/caddy/Caddyfile
        networks:
            - reverse_proxy

    web-app:
        container_name: web-app
        build:
            context: ./react
            dockerfile: ./docker/dev.Dockerfile
        environment:
            VITE_API_URL: "https://naszrod.local/api"
        depends_on:
            - server
        ports:
            - 5173:5173
        volumes:
            - ./react:/app
        networks:
            - reverse_proxy
        stdin_open: true # prevent container running dev from exiting
        tty: true # prevent container running dev from exiting

volumes:
    caddy_data:
    caddy_config:
    pg_data:

networks:
    reverse_proxy:
